### PR TITLE
Translation to Brazilian Portuguese

### PR DESCRIPTION
**Pull request by calheira**
Hi Jason,

@calexandrequeiroz and I enjoyed the Phreeze and would like to contribute to the project. We can translate the files, websites and tutorials for Portuguese and thus help spread this amazing software in Brazil.

Kind Regards,

### CODE REVIEW

**Comment by jasonhinkle** [comment]
Nice - thanks for the translation!  I might do some research as to how other projects do multiple languages for the README, perhaps there are multiple README files for each language?  Not sure.  I'll look into it and see what the usual solution is.

**Comment by joaoricardorm** [comment]
Hello again, I'm using the Phreeze on my college graduation final project, like I said a few months ago.
I'll do my own translation to portuguese too. If it helps, I can upload my files too. I never used GitHub or similar, so maybe I'll need some help to do.
Thanks again by the great job, Jason.

**Comment by calexandrequeiroz** [comment]
Hey Joao! Are you brazilian? If yes, let talk in portuguese.

I already made some translations to pt-br.

Let me know if it will help you!

Thanks!


Em segunda-feira, 17 de agosto de 2015, joaoricardorm <
notifications@github.com> escreveu:

> Hello again, I'm using the Phreeze on my college graduation final project,
> like I said a few months ago.
> I'll do my own translation to portuguese too. If it helps, I can upload my
> files too. I never used GitHub or similar, so maybe I'll need some help to
> do.
> Thanks again by the great job, Jason.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jasonhinkle/phreeze/pull/191#issuecomment-131947366>.
>


-- 



*Alexandre Queiroz*

Telefone:  +55 21 99235-5342

e-mail:     *calexandrequeiroz@gmail.com <calexandrequeiroz@gmail.com>*

Portfólio:  http://alexandrequeiroz.carbonmade.com

**Comment by joaoricardorm** [comment]
Yes I'm brazilian, but I'm talking in english because some forums asks this because this way more people can understand the topic.
Anyway, if you prefer I can talk in portuguese.
I'd like to know how you doing the translation, if is using a separated file with the portuguese's strings or you're replacing all the strings in english directly in the Pheeze core files?
I made a repository of Pheeze in my account to put my files, I don't know if is that the right way to do it, or if this is allowed by the author. Or I must use a branch in the master Pheeze repository?

**Comment by calheira** [comment]
Hi @joaoricardorm !

Good to see more Brazilians in this project! :smiley: 
I translated some of the documentation for the Portuguese of Brazil.
Some files are only partially translated .
You can take a fork in the original repository, make their changes, and then make a pull request .
If you want , I can give you some tips on how to use git, via skype brunocalheira[at]hotmail[dot]com or gtalk bruno[at]calheira[dot]com

:+1:

**Pull request merged**
