### PR TITLE
Added in a feature to store table names for both sigular and plural n…

### PR DESCRIPTION
**Pull request by stevetx30**
Added in a feature to store table names for both singular and plural names in local storage.

When Generate Application is clicked,
store the names after no errors.  Tie it to the Application Name

Next time when building the application just click useLastTableNames button and the table names inputs will update based on last time generated.

Saves time and mistakes by not having to retype names again.

### CODE REVIEW

**Comment by stevetx30** [comment]
Updated Builder to use the latest jquery, backbone, and underscore

Also the builder was downloading 2 jQueries on was 1.8.2 and the other was 1
.9.1


went with jquery.min.js so it makes updates only to 1 file as apposed to 2 in future releases.

**Comment by stevetx30** [comment]
Made its a bit more intuitive,  would only enable the button if there was local storage present for that application.

**Comment by jasonhinkle** [comment]
I'm going to review this this weekend and if everything looks cool I'll merge. This is something that I have wanted to do but never had the time, people will like this feature. Thanks for the PR!

**Comment by stevetx30** [comment]
Jason.
Going to start on a new option
Vue.js with PureCss.  Going to move this away from Server Side templates as 1 option.  Want a very light approach.

I am thinking given my workload .  3 months is what I can do it in.  I did port over to Bootstrap3 however BootStrap 4 is now almost out.

I think it would be good press if we did Vue.js/Purecss and Boostrap 4/jQuery.  

Also looking at how to take what you done and build a NodeJs with hapijs,  this is another option  as well 

Thoughts?

Steve

**Comment by jasonhinkle** [comment]
That is cool, I have a ton of work and some health issues that are preventing me from getting to this as quickly as I'd like but rest assured I want this in the main branch and will get to it as soon as I can.

Yea, I'm kinda waiting for bootstrap 4 as well! I have converted some generated apps to bootstrap 3, but I never manage to find the time to get it added to the builder.

So it seems you have recognized that the builder app really can create anything - it's just a generic template system.  I used to use it to generate C# apps, so a template for Node apps would be no problem. Obviously Yeoman is the generator of choice for Node apps but I think that Phreeze builder is nice for those of us who want to have a pre-built app that already knows your DB schema.

I was also considering separating builder from phreeze and making them separate apps. So many plans, so little time!

**Comment by stevetx30** [comment]
Replaced older version of Smarty dated Oct 2014 with Dec2015

**Pull request closed without merging**
